import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Logo from "@/components/Logo/Logo";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Logo />
        <span className="absolute top-8 right-8 border-[1px] w-[20px] h-[20px] block border-black z-10"></span>

        {children}

        {/* <script src="https://cdnjs.cloudflare.com/ajax/libs/three.js/r134/three.min.js"></script> */}
      </body>
    </html>
  );
}
